[build]
  command = "npm run build"  # Your frontend build command
  publish = "build"         # Your frontend build output directory

# Environment variables
[build.environment]
  REACT_APP_API_URL = "https://weatherapp2-1-v07l.onrender.com"

# Redirect all API calls to your Django backend
[[redirects]]
  from = "/api/*"
  to = "https://weatherapp2-1-v07l.onrender.com/api/:splat"
  status = 200
  force = true

# Single Page Application (SPA) fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://weatherapp2-1-v07l.onrender.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https://weatherapp2-1-v07l.onrender.com data:;"
    Access-Control-Allow-Origin = "https://your-netlify-site.netlify.app"  # Replace with your Netlify URL
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache settings
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Required for Django CSRF
[[headers]]
  for = "/csrf/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://your-netlify-site.netlify.app"  # Replace with your Netlify URL
    Access-Control-Allow-Credentials = "true"