
[build]
  base = "frontend/resqlink"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  REACT_APP_API_URL = "https://weatherapp2-1-v07l.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://weatherapp2-1-v07l.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://weatherapp2-1-v07l.onrender.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https://weatherapp2-1-v07l.onrender.com data:;"
    Access-Control-Allow-Origin = "https://resqlinkfront.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/csrf/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://resqlinkfront.netlify.app"
    Access-Control-Allow-Credentials = "true"
