# Generated by Django 5.1.4 on 2025-01-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_is_admin_customuser_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
