# Generated by Django 5.0.6 on 2025-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customuser_is_admin_remove_customuser_is_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('dob', models.DateField()),
                ('doa', models.DateField()),
                ('skill', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
