# Generated by Django 5.1.3 on 2025-02-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunt',
            name='blood_group',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunt',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='volunt',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
