# Generated by Django 5.1.3 on 2025-02-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productpayment_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPayment',
        ),
    ]
