# Generated by Django 5.1.3 on 2025-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship_images/'),
        ),
        migrations.AddField(
            model_name='volunt',
            name='citizenship',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship_images/'),
        ),
    ]
