# Generated by Django 5.1.3 on 2025-03-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contactmessage_customuser_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='citizenship',
        ),
    ]
