# Generated by Django 5.1.3 on 2025-03-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
