# Generated by Django 5.1.3 on 2025-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="identity",
            field=models.ImageField(
                blank=True, null=True, upload_to="identity_images/"
            ),
        ),
    ]
