# Generated by Django 5.1.3 on 2025-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_customuser_identity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="identity",
        ),
        migrations.AddField(
            model_name="customuser",
            name="citizenship",
            field=models.ImageField(
                blank=True, null=True, upload_to="citizenship_images/"
            ),
        ),
    ]
