# Generated by Django 5.1.3 on 2025-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunt',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
