# Generated by Django 5.1.3 on 2025-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_volunt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunt',
            name='address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
