# Generated by Django 5.1.3 on 2025-04-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_contactmessage_accuracy_contactmessage_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
